### ISSUE TITLE
Type error with other pak except NMSARC.fonts.pak

### ISSUE THREAD

**Issue by zerlkung** [monkeyman192/HGPAKtool#2]
```
Traceback (most recent call last):
  File "D:\PKGs\Fake PKG Tools\MyTools\No Man Sky\HGPAKtool\HGPAKTool\hgpaktool.py", line 656, in <module>
    f.read()
  File "D:\PKGs\Fake PKG Tools\MyTools\No Man Sky\HGPAKtool\HGPAKTool\hgpaktool.py", line 357, in read
    first_chunks += self.decompress_chunk(i)
TypeError: can't concat NoneType to bytes
Press any key to continue . . .
```

platform PS4

**Comment by monkeyman192** [comment]
This tool only supports switch and Mac .pak files. For ps4 use the usual psarctool

**Comment by zerlkung** [comment]
But on ps4 is HGPAK i understand is same type of switch, Thank you sir.

**Comment by czdvoika** [comment]
Ps4 is hgpak but zstd compress :-)

**Comment by monkeyman192** [comment]
hmmm, can you please post a ps4 .pak file as well? Maybe one compressed and one uncompressed?

**Comment by zerlkung** [comment]
> hmmm, can you please post a ps4 .pak file as well? Maybe one compressed and one uncompressed?

[NMSARC.fonts.pak](https://www.mediafire.com/file/bio9a6iz3myhqoz/NMSARC.fonts.pak/file) is uncompressed from @czdvoika say.

[NMSARC.Language.pak](https://www.mediafire.com/file/vxvlsctavyb24h1/NMSARC.Language.pak/file) is compressed.

**Comment by monkeyman192** [comment]
hmm, interesting! PS4 always used to use the same format as psarctool (ie. zlib/lzma)
I'll look into adding this format too when I have time.

**Comment by monkeyman192** [comment]
Well I guess if I'd actually addressed this when this issue was raised, we'd have had less issues when pc changed to this format! I guess this is now fixed!
